config/routes.rb
Rails.application.routes.draw do
  resources :client_workouts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_workout.rb
class ClientWorkout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/client_workouts_controller.rb
class ClientWorkoutsController < ApplicationController
  before_action :set_client_workout, only: [:show, :edit, :update, :destroy]

  # GET /client_workouts
  # GET /client_workouts.json
  def index
    @client_workouts = ClientWorkout.where(trainer: "Ironman")
  end

  # GET /client_workouts/1
  # GET /client_workouts/1.json
  def show
  end

  # GET /client_workouts/new
  def new
    @client_workout = ClientWorkout.new
  end

  # GET /client_workouts/1/edit
  def edit
  end

  # POST /client_workouts
  # POST /client_workouts.json
  def create
    @client_workout = ClientWorkout.new(client_workout_params)

    respond_to do |format|
      if @client_workout.save
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully created.' }
        format.json { render :show, status: :created, location: @client_workout }
      else
        format.html { render :new }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_workouts/1
  # PATCH/PUT /client_workouts/1.json
  def update
    respond_to do |format|
      if @client_workout.update(client_workout_params)
        format.html { redirect_to @client_workout, notice: 'Client workout was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_workout }
      else
        format.html { render :edit }
        format.json { render json: @client_workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_workouts/1
  # DELETE /client_workouts/1.json
  def destroy
    @client_workout.destroy
    respond_to do |format|
      format.html { redirect_to client_workouts_url, notice: 'Client workout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_workout
      @client_workout = ClientWorkout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_workout_params
      params.require(:client_workout).permit(:trainer,:client, :duration, :dateWorkout, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_workouts_helper.rb
module ClientWorkoutsHelper
end

app/views/client_workouts/_form.html.erb
<div class="container-fluid">

<%= form_with(model: client_workout, local: true) do |form| %>
  <% if client_workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_workout.errors.count, "error") %> prohibited this client_workout from being saved:</h2>

      <ul>
      <% client_workout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="card" style="width: 30rem;">
  <div class="card-body">
  
  <div class="field">
    <%= form.label :trainer %>
    <%= form.text_field :trainer, class: "form-control" %>
  </div>
  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :dateWorkout %>
    <%= form.datetime_select :dateWorkout, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success text-black" %>
  </div>
<% end %>

  </div>
</div>

</div>

app/views/client_workouts/edit.html.erb
<h2>Edit Client</h2>

<div class="container-fluid">
	<button class="btn btn-success">
		<%= link_to 'Show', @client_workout %> 
	</button>

	<button class="btn btn-warning">
		<%= link_to 'Back', client_workouts_path %>
	</button>
</div>

<%= render 'form', client_workout: @client_workout %>

app/views/client_workouts/index.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<h1>Client Workouts</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Trainer</th>
      <th>Client</th>
      <th>Duration</th>
      <th>Dateworkout</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_workouts.each do |client_workout| %>
      <tr>
        <td><%= client_workout.trainer %></td>
         <td><%= client_workout.client %></td>
        <td><%= client_workout.duration %></td>
        <td><%= client_workout.dateWorkout %></td>
        <td><%= client_workout.amount %></td>
        <td>
        <button class="btn btn-warning btn-block">
          <%= link_to 'Show', client_workout %>
        </button>
        </td>
        <td>
        <button class="btn btn-success btn-block">
          <%= link_to 'Edit', edit_client_workout_path(client_workout) %>
        </button>
        </td>
        <td>
        <button class="btn btn-danger btn-block">
          <%= link_to 'Destroy', client_workout, method: :delete, data: { confirm: 'Are you sure?' } %>
        </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<button class="btn btn-success text-white">
<%= link_to 'New Client Workout', new_client_workout_path %>
</button>
</div>

app/views/client_workouts/new.html.erb
<h2>Add New Client</h2>

<div class="container-fluid">
	<button class="btn btn-warning">
		<%= link_to 'Back', client_workouts_path %>
	</button>
</div>
<br>
<%= render 'form', client_workout: @client_workout %>

app/views/client_workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trainer:</strong>
  <%= @client_workout.trainer %>
</p>
<p>
  <strong>Client:</strong>
  <%= @client_workout.client %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @client_workout.duration %>
</p>

<p>
  <strong>Dateworkout:</strong>
  <%= @client_workout.dateWorkout %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @client_workout.amount %>
</p>

<%= link_to 'Edit', edit_client_workout_path(@client_workout) %> |
<%= link_to 'Back', client_workouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gym</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="/app/assets/javascripts/jquery.js"></script>
    <script src="/app/assets/javascripts/popper.js"></script>
    <script src="/app/assets/javascripts/bootstrap.js"></script>
   
    <link rel="stylesheet" href="/app/assets/stylesheets/bootstrap.css">

    <style type="text/css">
    a:hover {
      text-decoration: none;
      background-color: transparent;
    }
    a {
      color:black !important;
    }
    body {
      margin: 0px;
    }
    </style>

  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark text-white justify-content-between">
      <a class="navbar-brand">Navbar</a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </nav>

    <%= yield %>
  </body>
</html>